# Not Enable this for now
require: rubocop-rspec 

AllCops:
  Exclude:
    - db/schema.rb          # Ignore specific file
    - vendor/**/*           # Ignore all files in the vendor directory
    - node_modules/**/*     # Ignore all files in node_modules
    - spec/**/*             # Ignore all files in spec directory
    - features/**/*         # Ignore all files in spec directory

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/HashAlignment:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented  # Indent method calls, but do not align with the receiver

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation  # Use fixed indentation for arguments, no alignment based on first argument

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation  # Align parameters in method definitions and calls

Layout/DotPosition:
  EnforcedStyle: leading

Style/RedundantSelf:
  Enabled: false  # Disables the cop that removes redundant `self`

# Style/TrailingCommaInArguments:
#   EnforcedStyleForMultiline: comma  # Enforce trailing comma in multiline method arguments

Layout/LineLength:
  Max: 120  # Set the max line length to 80 characters

Metrics/MethodLength:
  Max: 40  # Maximum number of lines allowed in a method

Metrics/ClassLength:
  Max: 150  # Maximum number of lines allowed in a class or module

# Metrics/BlockLength:
#   Max: 300  # Maximum number of lines allowed in a block or file

# Metrics/FileLength:
#   Max: 500  # Maximum number of lines allowed in an entire file

Metrics/AbcSize:
  Max: 40  # Maximum ABC size in a method

Metrics/CyclomaticComplexity:
  Max: 8  # The maximum allowed complexity for a method
