version: "3"
services:
  postgres: 
    environment:
      POSTGRES_DB: eventnxt_db_test
       
  test_rspec:
    build: .
    environment:
      - RAILS_ENV=test
      - BUNDLE_WITHOUT=development
    command: bash -c "bundle install && bundle exec rspec"
    volumes:
      - .:/eventnxt
      - bundle_data:/usr/local/bundle
    depends_on:
      - postgres

  test_cucumber:
    build: .
    environment:
      - RAILS_ENV=test
      - BUNDLE_WITHOUT=development
    command: bash -c "bundle install && bundle exec cucumber"
    volumes:
      - .:/eventnxt
      - bundle_data:/usr/local/bundle
    depends_on:
      - postgres