version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-eventnxt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: eventnxt_db_test
    volumes:
      - db_data_test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
       
  test_rspec:
    build: .
    environment:
      - RAILS_ENV=test
      - BUNDLE_WITHOUT=development
    command: bash -c "bundle install && bundle exec rails db:drop db:prepare && bundle exec rspec"
    volumes:
      - .:/eventnxt
      - bundle_data_rspec:/usr/local/bundle
    depends_on:
      - postgres

  test_cucumber:
    build: .
    environment:
      - RAILS_ENV=test
      - BUNDLE_WITHOUT=development
    command: bash -c "bundle install && bundle exec rails db:drop db:prepare && bundle exec cucumber"
    volumes:
      - .:/eventnxt
      - bundle_data_cucumber:/usr/local/bundle
    depends_on:
      - postgres

volumes:
  db_data_test:
  bundle_data_rspec:
  bundle_data_cucumber: 
  