default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'eventnxt' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>
  host: db # refers to the db service from docker-compose.yml (which is the PostgreSQL container).
  port: 5432

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'eventnxt_db_dev' } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'eventnxt_db_test' } %>

production:
  url: <%= ENV['DATABASE_URL'] %>
