#!/usr/bin/env ruby
# frozen_string_literal: true

docker_run = 'docker-compose -f docker-compose.test.yml run --rm test_cucumber'

if ARGV.length.positive?
  cmd = 'bundle install && bundle exec rails db:drop && bundle exec rails db:prepare && bundle exec cucumber'
  ARGV.each do |arg|
    cmd += if arg.include?(' ')
             " \"#{arg}\""
           else
             " #{arg}"
           end
  end
  cmd = "bash -c '#{cmd}'"
end

cmd = "#{docker_run} #{cmd}"

puts("Running Cmd: #{cmd}")
system(cmd)
