#!/usr/bin/env ruby

docker_run = "docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm test_rspec"

if ARGV.length > 0
  cmd ='bundle install && bundle exec rspec'
  ARGV.each do |arg| 
    if arg.include?(" ")
      cmd += " \"#{arg}\""
    else
      cmd += " #{arg}"
    end
  end
  cmd = "bash -c '#{cmd}'"
end

cmd = "#{docker_run} #{cmd}"

puts("Running Cmd: #{cmd}")
system(cmd)