name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: eventnxt
          POSTGRES_PASSWORD: password
          POSTGRES_DB: eventnxt_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U eventnxt" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.test.yml up --build -d

      - name: Run RSpec Tests
        run: docker-compose -f docker-compose.test.yml run test_rspec

      - name: Run Cucumber Tests
        run: docker-compose -f docker-compose.test.yml run test_cucumber

      - name: Tear Down Docker Compose
        run: docker-compose -f docker-compose.test.yml down