name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  rspec-and-cucumber:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose with Combined Configurations
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build -d

      - name: Run RSpec Tests
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run test_rspec

      - name: Run Cucumber Tests
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run test_cucumber

      - name: Tear Down Docker Compose
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml down