name: RSpec and Cucumber

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment for colorized output
        run: echo "Setting RAILS_ENV and CI for color output"
        env:
          RAILS_ENV: test
          CI: true  # Forces color output in some tools like Bundler and Rails
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Tear Down Docker Compose
        run: |
          docker-compose -f docker-compose.test.yml down -v --remove-orphans
          docker volume prune -f

      - name: Set up Docker Compose with Combined Configurations
        run: docker-compose -f docker-compose.test.yml up --build -d

      - name: Run RSpec Tests
        run: docker-compose -f docker-compose.test.yml run test_rspec

      - name: Run Cucumber Tests
        run: docker-compose -f docker-compose.test.yml run test_cucumber

      - name: Tear Down Docker Compose
        if: always()
        run: |
          docker-compose -f docker-compose.test.yml down -v --remove-orphans
          docker volume prune -f
