name: RuboCop Autocorrect

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch All Branches
        run: |
          # Fetch the full history for both main and dev branches
          git fetch origin main:main
          git fetch origin dev:dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Adjust to your Ruby version

      - name: Install RuboCop
        run: |
          gem install rubocop

      - name: Get Changed Ruby Files
        id: changed_files
        run: |
          # Use the base branch for comparison (either main or dev)
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          git diff --name-only $BASE_BRANCH...HEAD -- '*.rb' > changed_files.txt

      - name: Run RuboCop with Autocorrect on Changed Files
        if: success()
        run: |
          if [[ -s changed_files.txt ]]; then
            rubocop -A $(cat changed_files.txt)
          else
            echo "No Ruby file changes detected"
          fi

      - name: Commit and Push Changes
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-corrected RuboCop issues in modified files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}